language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - phpenv config-rm xdebug.ini
  - composer global require "fxp/composer-asset-plugin:~1.1.0" "codeception/codeception:^2.0" "codeception/specify" "codeception/verify"
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

# setup application:
  - |
    cp .env.dist .env
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

before_script:
  - mysql -e 'CREATE DATABASE `yii2-starter-kit`;';
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    ./vendor/bin/codecept build
    ./vendor/bin/codecept run --debug
