data:
  container_name: 'data'
  restart: always
  image: busybox:latest
  volumes:
    - ./:/app

php:
  container_name: 'fpm'
  restart: always
  build: docker/php
#  image: php:7-fpm
  working_dir: /app
  expose:
    - '9000'
  volumes_from:
    - data
  links:
    - db
    - mailcatcher

nginx:
  container_name: 'nginx'
  restart: always
  image: nginx:latest
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - ./vhost.conf.docker.dist:/etc/nginx/conf.d/default.conf
  volumes_from:
    - data
  links:
    - php

mailcatcher:
  container_name: 'mail'
  restart: always
  image: schickling/mailcatcher:latest
  ports:
    - '1080:1080'
    - '1025:1025'

db:
  container_name: 'db'
  restart: always
  image: mysql:latest
  ports:
    - '3306:3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: 'yii2-starter-kit'
    MYSQL_USER: 'ysk_dbu'
    MYSQL_PASSWORD: 'ysk_pass'
