data:
  image: busybox:latest
  volumes:
    - ./:/app
  entrypoint: tail -f /dev/null

fpm:
  build: docker/fpm
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - db
    - mailcatcher
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

cli:
  build: docker/cli
  volumes_from:
    - data
  working_dir: /app
  tty: true
  stdin_open: true
  command: '/bin/bash'
  links:
    - db
    - mailcatcher

nginx:
  image: nginx:latest
  ports:
    - "8000:80"
  volumes:
    - ./:/app
    - ./docker/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - fpm

mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - "33060:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: yii2-starter-kit
    MYSQL_USER: ysk_dbu
    MYSQL_PASSWORD: ysk_pass